services:
  - type: web
    name: user-auth-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: db_ioio
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: MAX_FAILED_LOGIN_ATTEMPTS
        value: 5
      - key: LOCK_TIME_LOGIN_WINDOW
        value: 15
      - key: LOCK_USER_TIME
        value: 30 